# - name: "NOTSCORED | 6.1.1 | PATCH | Audit system file permissions"
#   command: /bin/true
#   changed_when: no


- name: "SCORED | 6.1.2 | PATCH | Ensure permissions on /etc/passwd are configured"
  file:
      dest: /etc/passwd
      owner: root
      group: root
      mode: 0644

- name: "SCORED | 6.1.3 | PATCH | Ensure permissions on /etc/shadow are configured"
  file:
      dest: /etc/shadow
      owner: root
      group: root
      mode: 0000


- name: "SCORED | 6.1.4 | PATCH | Ensure permissions on /etc/group are configured"
  file:
      dest: /etc/group
      owner: root
      group: root
      mode: 0644


- name: "SCORED | 6.1.5 | PATCH | Ensure permissions on /etc/gshadow are configured"
  file:
      dest: /etc/gshadow
      owner: root
      group: root
      mode: 0000


- name: "SCORED | 6.1.6 | PATCH | Ensure permissions on /etc/passwd- are configured"
  file:
      dest: /etc/passwd-
      owner: root
      group: root
      mode: 0600


- name: "SCORED | 6.1.7 | PATCH | Ensure permissions on /etc/shadow- are configured"
  file:
      dest: /etc/shadow-
      owner: root
      group: root
      mode: 0000


- name: "SCORED | 6.1.8 | PATCH | Ensure permissions on /etc/group- are configured"
  file:
      dest: /etc/group-
      owner: root
      group: root
      mode: 0600


- name: "SCORED | 6.1.9 | PATCH | Ensure permissions on /etc/gshadow- are configured"
  file:
      dest: /etc/gshadow-
      owner: root
      group: root
      mode: 0600
#
#
# - name: "SCORED | 6.1.10 | PATCH | Ensure no world writable files exist"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "SCORED | 6.1.11 | PATCH | Ensure no unowned files or directories exist"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "SCORED | 6.1.12 | PATCH | Ensure no ungrouped files or directories exist"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "NOTSCORED | 6.1.13 | PATCH | Audit SUID executables"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "NOTSCORED | 6.1.14 | PATCH | Audit SGID executables"
#   command: /bin/true
#   changed_when: no

# - name: "SCORED | 6.2.2 | PATCH | Ensure no legacy '+' entries exist in /etc/passwd"
#   command: sed -i '/^+/ d' /etc/passwd
#   changed_when: no
#   failed_when: no


- name: "SCORED | 6.2.3 | PATCH | Ensure no legacy '+' entries exist in /etc/shadow"
  command: sed -i '/^+/ d' /etc/shadow
  changed_when: no
  failed_when: no


- name: "SCORED | 6.2.4 | PATCH | Ensure no legacy '+' entries exist in /etc/group"
  command: sed -i '/^+/ d' /etc/group
  changed_when: no
  failed_when: no


# - name: "SCORED | 6.2.5 | PATCH | Ensure root is the only UID 0 account"
#   command: passwd -l {{ item }}
#   changed_when: no
#   failed_when: no
#   with_items: "{{ uid_zero_accounts_except_root.stdout_lines }}"
#   when:
#       - uid_zero_accounts_except_root.rc
#
#
# - name: "SCORED | 6.2.6 | PATCH | Ensure root PATH Integrity"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "SCORED | 6.2.7 | PATCH | Ensure all users' home directories exist"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "SCORED | 6.2.8 | PATCH | Ensure users' home directories permissions are 750 or more restrictive"
#   command: /bin/true
#   changed_when: no
#
# - name: "SCORED | 6.2.9 | PATCH | Ensure users own their home directories"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "SCORED | 6.2.10 | PATCH | Ensure users' dot files are not group or world writable"
#   command: /bin/true
#   changed_when: no

#
# - name: "SCORED | 6.2.11 | PATCH | Ensure no users have .forward files"
#   file:
#       state: absent
#       dest: "~{{ item }}/.forward"
#   with_items: "{{ users.stdout_lines }}"
#
# - name: "SCORED | 6.2.12 | PATCH | Ensure no users have .netrc files"
#   file:
#       state: absent
#       dest: "~{{ item }}/.netrc"
#   with_items: "{{ users.stdout_lines }}"
#
# - name: "SCORED | 6.2.14 | PATCH | Ensure no users have .rhosts files"
#   file:
#       state: absent
#       dest: "~{{ item }}/.rhosts"
#   with_items: "{{ users.stdout_lines }}"

#
# - name: "SCORED | 6.2.15 | PATCH | Ensure all groups in /etc/passwd exist in /etc/group"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "SCORED | 6.2.16 | PATCH | Ensure no duplicate UIDs exist"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "SCORED | 6.2.17 | PATCH | Ensure no duplicate GIDs exist"
#   command: /bin/true
#   changed_when: no
#
#
# - name: "SCORED | 6.2.18 | PATCH | Ensure no duplicate user names exist"
#   command: /bin/true
#   changed_when: no
#
# - name: "SCORED | 6.2.19 | PATCH | Ensure no duplicate group names exist"
#   command: /bin/true
#   changed_when: no
